//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImMusik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clases()
        {
            this.RegistrosClases = new HashSet<RegistrosClases>();
        }
    
        public int Id { get; set; }
        public int IdSucursal { get; set; }
        public string Nombre { get; set; }
        public int NumAlumnos { get; set; }
        public int IdProfesor { get; set; }
        public int Hora { get; set; }
        public string Dias { get; set; }
    
        public virtual Profesores Profesores { get; set; }
        public virtual Sucursales Sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrosClases> RegistrosClases { get; set; }
    }
}
