//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImMusik2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class immusikEntities : DbContext
    {
        public immusikEntities()
            : base("name=immusikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<Clases> Clases { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<Profesores> Profesores { get; set; }
        public virtual DbSet<RegistrosClases> RegistrosClases { get; set; }
        public virtual DbSet<Sucursales> Sucursales { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
